# Pythonは公式イメージ
FROM python_application_base:0.1

LABEL  maintainer "nnashiki <n.nashiki.work@gmail.com>"

COPY main /main
WORKDIR main

COPY main/Pipfile Pipfile

RUN set -x && \
    pipenv install --system --skip-lock
